//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DispatcherDesktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DispatcherDesktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРИНЯТЬ.
        /// </summary>
        public static string AcceptButtonLbl {
            get {
                return ResourceManager.GetString("AcceptButtonLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРИМЕНИТЬ.
        /// </summary>
        public static string ApplyBtnText {
            get {
                return ResourceManager.GetString("ApplyBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение диспечтчеризации тепловых узлов академии МЧС.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОТМЕНИТЬ.
        /// </summary>
        public static string CancelButtonLbl {
            get {
                return ResourceManager.GetString("CancelButtonLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to соединение.
        /// </summary>
        public static string ConnectionSettingsSectionHeader {
            get {
                return ResourceManager.GetString("ConnectionSettingsSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to поле не должно быть пустым.
        /// </summary>
        public static string EmptyInputErrorMsg {
            get {
                return ResourceManager.GetString("EmptyInputErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это поле обязательно для заполнения.
        /// </summary>
        public static string FieldIsRequredErrorMsg {
            get {
                return ResourceManager.GetString("FieldIsRequredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to лог.
        /// </summary>
        public static string LogSettingsSectionHeader {
            get {
                return ResourceManager.GetString("LogSettingsSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите новое значение.
        /// </summary>
        public static string NewValueLblText {
            get {
                return ResourceManager.GetString("NewValueLblText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция чтения была прервана, так как заняла слишком много времени.
        /// </summary>
        public static string ReadOperationFailureByTimeoutLogMsg {
            get {
                return ResourceManager.GetString("ReadOperationFailureByTimeoutLogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция чтения была завершена с ошибкой.
        /// </summary>
        public static string ReadOperationFailureLogMsg {
            get {
                return ResourceManager.GetString("ReadOperationFailureLogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция чтения была успешно завершена.
        /// </summary>
        public static string ReadOperationSuccesLogMsg {
            get {
                return ResourceManager.GetString("ReadOperationSuccesLogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимы только значения, больше чем.
        /// </summary>
        public static string ShouldBeMoreErrorMsg {
            get {
                return ResourceManager.GetString("ShouldBeMoreErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только числа допустимы для ввода.
        /// </summary>
        public static string ShouldBeNumberErrorMsg {
            get {
                return ResourceManager.GetString("ShouldBeNumberErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to период опроса (секунды).
        /// </summary>
        public static string SurveyPeriodLblText {
            get {
                return ResourceManager.GetString("SurveyPeriodLblText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to период опроса (сек).
        /// </summary>
        public static string SurveyPeriodSettingLblText {
            get {
                return ResourceManager.GetString("SurveyPeriodSettingLblText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to автоматический опрос.
        /// </summary>
        public static string SurveyStartedLabel {
            get {
                return ResourceManager.GetString("SurveyStartedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записать значение.
        /// </summary>
        public static string WriteNewRegisterValueHeader {
            get {
                return ResourceManager.GetString("WriteNewRegisterValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция записи была прервана, так как заняла слишком много времени.
        /// </summary>
        public static string WriteOperationFailureByTimeoutLogMsg {
            get {
                return ResourceManager.GetString("WriteOperationFailureByTimeoutLogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция записи была завершена с ошибкой.
        /// </summary>
        public static string WriteOperationFailureLogMsg {
            get {
                return ResourceManager.GetString("WriteOperationFailureLogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция записи была успешно завершена.
        /// </summary>
        public static string WriteOperationSuccesLogMsg {
            get {
                return ResourceManager.GetString("WriteOperationSuccesLogMsg", resourceCulture);
            }
        }
    }
}
